### ISSUE TITLE
Some swimmers' academic year are messed up

### ISSUE THREAD

**Issue by david-thornton** [Chaviland7/NUSC_Website#10]

**Comment by david-thornton** [comment]
@Chaviland7 Is this something that is changed manually?

**Comment by Chaviland7** [comment]
@david-thornton yeah that's a custom field on the athletes in TM. When we get the computer we can just manually change it for everyone.

**Comment by Chaviland7** [comment]
I've thought of ways to automate the process of incrementing everyone's year but I'm realizing that I can put a button in the admin portal that runs a script to increment that column in that table
