### ISSUE TITLE
Put new Swimmer Pictures onto Wordpress

### ISSUE THREAD

**Issue by Chaviland7** [Chaviland7/NUSC_Website#15]
*The goal is to get swimmer pictures labeled lastname_firstname.jpg at size 266x400 (or 1.5:1 aspect ratio) uploaded to the WordPress Media Library. The instructions are meant to be overly detailed so if that sounds easy then take it away!*

Step 1: Gather the pictures and name them with the convention `lastname_firstname.jpg`. This is the file name that the site will search for with each swimmer. If they have a fancy official name but go by a "nickname" then use that nickname as the firstname (charlie instead of charles, for example). Also any hyphens in their name should be replaced with underscores ('van_winkle_shelbe').

Step 2: Resize the pictures. This is important for 2 reasons. 1: If the proportions are wrong it won't look right on the website. 2: Even if the proportions are right, if the file size is huge then it will take forever to load (you've probably noticed the website already takes a very long time to load).

The ideal size here is 266x400 (that's just the aspect ratio that the pictures used to be so I kept it).
If you are comfortable resizing and/or cropping the images* with Mac's native Preview app (instructions can be found online) then feel free to do it there (probably the easiest option). But if you don't want to mess with that, then you can skip this step and resize the images after uploading them (in step 4).

*It is probably best to resize the image first and then crop it if both are necessary. Otherwise taking a 266x400 piece of a huge file could just result in a picture of someone's nose or something (@nicknewhart).

Step 3: Upload the suckers to WordPress! This can very easily be done by opening the Media Library page -> opening a small finder window on top of the browser -> selecting all the images -> and dragging them onto the browser page (you should see a blue cover appear with some message about uploading these images). Give it a minute to upload each image and then you're all set!

-------

Step 4: Okay if you didn't resize the images before uploading them, then you can still do this on WordPress (although it's a bit more tedious). To do this you follow these steps...
4.1. Click on the Image in the Media Library
4.2. Click "Edit Image" underneath the image itself
4.3. If the image is very large, then use the 'Scale Image' section to execute the following steps, but if the image is already close to the desired dimensions then proceed to step 4.4.
4.3.1 The goal is to scale the image size down without losing part of it. As I said with my * earlier, doing them in the wrong order can result in a really small image. So:
4.3.2 Type 266 into the first box under 'scale image' and see what the second box becomes. If the second box is bigger than 400 then hit scale and skip to 4.4.
4.3.3 If the second number is less than 400 then you should instead type 400 into the second box and hit scale (assuming the first number is now bigger than 266). Now the image is scaled down and nothing has been lost!
4.4. Draw a small box with your mouse anywhere on the image by clicking and dragging on the image.
4.5 Replace whatever numbers appeared in the 'selection' boxes with the desired dimensions (266 and 400 in this case).
4.6 Now drag the box so that it covers the right part of the image.
4.7 Hit the button with the 'crop' logo to the top-left of the image. You should see the cropped image appear.
4.8 If everything looks good then hit save and you are done!

**Comment by mcgridles** [comment]
Pictures uploaded

**Comment by Chaviland7** [comment]
Thats a dangerously fast precedent my friend lol, thank you, they look great. Now once the new swimmers are in the database they'll actually appear on the site

**Comment by mcgridles** [comment]
Haha it definitely will not all get done this fast and don't feel the need to push yourself I was just getting some stuff done already and it takes like 3.5 seconds to do.
