### ISSUE TITLE
Oh no! A bug!

### ISSUE THREAD

**Issue by Chaviland7** [Chaviland7/NUSC_Website#18]
What! How did this happen! There's a bug! Charlie's picture won't display on the website!

**Obviously I planted this bug as a joke, there is 0 reason to do this with any urgency. It could sit there for a month and I would not notice so honestly no rush. Just a fun way to get you up and coding whenever you feel like it.**

Your mission, should you choose to accept it:
-Install northeastern's GlobalProtect VPN client and, using your husky credentials, open a secure connection to the server.
-Using git (in terminal or on the github site), clone this repository so that you have all the files in a folder somewhere on your computer.
-Install the Remote-FTP package in atom.
-Using Atom, open the website code folder so that all the files are showing in the left-hand flyout. In the top bar go to Packages->RemoteFTP->Create SFTP config file.
-Replace the empty template with the code in the comment below. Then hit save.
-Hit Packages->RemoteFTP->Toggle. In the sidebar that appears hit Connect.
-You should now be hooked up to the website code.
-Double click any file to open it, then edit the code where you like. Upon hitting save you should see a little progress bar in the bottom of the RemoteFTP sidebar saying "uploading _file_". When this finishes, your changes will be reflected on the live site!

For this particular bug you may want to peek at functions.php line 525 :)

**Comment by Chaviland7** [comment]
{
 "protocol": "sftp",
 "host": "nuweb30.neu.edu", // string - Hostname or IP address of the server. Default: 'localhost'
 "port": 22, // integer - Port number of the server. Default: 22
 "user": "clubswimming", // string - Username for authentication. Default: (none)
 "pass": "ef9Phipe", // string - Password for password-based user authentication. Default: (none)
 "promptForPass": false, // boolean - Set to true for enable password/passphrase dialog. This will prevent from using cleartext password/passphrase in this config. Default: false
 "remote": "/var/www/html/clubswimming/wp-content/themes/NuscTheme",
 "agent": "", // string - Path to ssh-agent's UNIX socket for ssh-agent-based user authentication. Windows users: set to 'pageant' for authenticating with Pageant or (actual) path to a cygwin "UNIX socket." Default: (none)
 "privatekey": "", // string - Path to the private key file (in OpenSSH format). Default: (none)
 "passphrase": "", // string - For an encrypted private key, this is the passphrase used to decrypt it. Default: (none)
 "hosthash": "", // string - 'md5' or 'sha1'. The host's key is hashed using this method and passed to the hostVerifier function. Default: (none)
 "ignorehost": true,
 "connTimeout": 10000, // integer - How long (in milliseconds) to wait for the SSH handshake to complete. Default: 10000
 "keepalive": 10000 // integer - How often (in milliseconds) to send SSH-level keepalive packets to the server (in a similar way as OpenSSH's ServerAliveInterval config option). Set to 0 to disable. Default: 10000
}

**Comment by mcgridles** [comment]
I LOVE THIS AND YOU also that was easy peasy. I'm going to try and go through some of the functions to try and understand the server/database side of things a little better. Basic coding I'm fine with it's pulling from the database and some of the more web oriented stuff I'm not too good with.

**Comment by mcgridles** [comment]
And I hope I not making you feel like you need to be doing this stuff and working so hard on the site I just have a lot of free time and enjoy doing this sort of thing on Valentine's Day.

**Comment by Chaviland7** [comment]
Haha glad to hear it was easy! You seem to have breezed through the setup so I hope the coding itself will provide some of the challenge and learning I'm sure you were looking for.

Yes feel free to take a look at the functions! I think ones like get_roster and get_front_page_slideshow will provide a decent introduction to all the concepts in there (including sql which you can ignore if it's too much at once) but especially how to use WordPress's php functions. The WordPress 'codex' also has great documentation if stuff is confusing. I know you're more than fine with the basics so if you get a basic hang of using wordpress then I think we're officially co-developers on the website!

And no worries about doing stuff fast, it's good to have someone pushing me on this! If I feel like it's too much then you'll know because I'll just slow down lol but all good for now
