### ISSUE TITLE
The entire site 

### ISSUE THREAD

**Issue by heyryanleys** [Chaviland7/NUSC_Website#19]

**Comment by heyryanleys** [comment]
rm -rf .git

**Comment by mcgridles** [comment]
??

**Comment by heyryanleys** [comment]
@mcgridles That was a joke, it's what you would type to delete the repo if you use git console. :stuck_out_tongue_winking_eye:

**Comment by Chaviland7** [comment]
But it wouldn't delete any of the code, just the github integration. Ryan has much to learn

**Comment by heyryanleys** [comment]
rm -rf @Chaviland7

**Comment by Chaviland7** [comment]
Well there's no coming back from that one. Good day gentlemen
